apiVersion: apps/v1
kind: Deployment
metadata:
  name: sepio-bot
spec:
  selector:
    matchLabels:
      app: sepio-bot
  template:
    metadata:
      labels:
        app: sepio-bot
    spec:
      containers:
        - name: sepio-bot
          image: 560914023379.dkr.ecr.us-east-2.amazonaws.com/discord-sepio
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: "/app/config.json"
              subPath: "config.json"
              name: sepio-bot-config-file
              readOnly: true
      volumes:
        - name: sepio-bot-config-file
          secret:
            secretName: discord-sepio-config-secret
